### ISSUE TITLE
Redo domain logic for listing assigned items

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/Droplet#129]
This should be a many-to-many relationship

## Subtasks
- [x] Plan domain logic change
- [x] Implement logic change for items listing
- [x] Implement logic change for items order
- [x] Fix issue new orders not assigning listings
- [x] Buy price needs to be updated on item quantity update
- [x] Write up migration script
- [x] Test up migration script
- [x] Write down migration script
- [x] Add quantity for items assigned to items table
- [x] Implement logic change for supply and order
- [x] Test up migration script
- [ ] Listing isn't added to order properly when creating the order
- [ ] Adding the same supply again should add to the value, not add a secondary
- [ ] Adding items to a listing should update the quantity listed
- [ ] Adding listings to an order should update the quantity sold for the item
- [ ] Calculating price of supplies in a supply purchase is wrong
