### ISSUE TITLE
AS an owner of a Droplet Instance, I want to be able to run the website from a binary

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/Droplet#61]
AS an owner of a Droplet instance, I want to be able to run the website from a binary
SO THAT I don't have to have all the development requirements installed on the machine

## Acceptance Criteria
AS an owner of a Droplet instance
GIVEN I want to start the server
WHEN I click execute the binary
THEN the server should load as if I ran it from the terminal with yarn

AS a project owner
GIVEN I a new release is required
WHEN I push to the main branch
THEN GitHub Actions should generate a binary using pkg

## Subtasks
- [ ] Manually create a binary
- [ ] Make sure the binary works as expected
- [ ] Automate using GitHub Actions
- [ ] Create documentation

## Notes
https://www.npmjs.com/package/pkg
